# This will run on Travis' 'new' container-based infrastructure
sudo: false 

# Blacklist
branches:
  only:
    - master

# Install dependencies
addons:
  apt:
    packages:
      - doxygen-1.8.15

# Build your code e.g. by calling make
script:
  - cd gst-libs/gst/videoanalytics
  - doxygen Doxyfile

# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: gst-libs/gst/videoanalytics/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
